Remove 'api' from urls and other small changes
DobaTech/thanos-api-docs pull request #78
Opened 2018-02-15 22:07 UTC by baileymatthewr

Remove 'api' from urls, use sandbox url as the default for the examples, correct the metadata for the documentation, and more.

2018-02-15 23:50 UTC, Gidgidonihah requested changes
The only thing I saw that's an issue are the borked adorable urls. They may be more that I didn't catch.

2018-02-15 23:50 UTC, Gidgidonihah commented on _product_retailer/get_item_detail.md
> +            "url": "https:/.adorable.io/avatars/80/obad15.png",
Looks like an overzealous search and replace got rid of the correct adorable urls.

2018-02-15 23:50 UTC, Gidgidonihah commented on _product_retailer/get_items.md
> +              "url": "https:/.adorable.io/avatars/285/obad15.png",
More borked adorable urls

2018-02-15 23:50 UTC, Gidgidonihah commented on _product_retailer/get_sku_detail.md
> -        "url": "https://api.adorable.io/avatars/80/obad20.png",
adoraborked.

2018-02-15 23:50 UTC, Gidgidonihah commented on _product_retailer/get_skus.md
> +          "url": "https:/.adorable.io/avatars/80/obad20.png",
adoraborked.

2018-02-15 23:50 UTC, Gidgidonihah commented on _product_retailer/search_items.md
> +            "url": "https:/.adorable.io/avatars/80/obad21.png",
adoraborked.

2018-02-15 23:50 UTC, Gidgidonihah commented
Looks like it also includes some work on #73

2018-02-16 00:37 UTC, baileymatthewr commented
@Gidgidonihah : I made the changes you recommended

2018-02-16 00:53 UTC, Gidgidonihah approved these changes

2018-02-16 18:06 UTC, jtprince approved these changes

2018-02-16 18:07 UTC, merged